### ISSUE TITLE
After Updating to v0.5.2 NoneType' object has no attribute 'encode

### ISSUE THREAD

**Issue by nicknick25** [rine77/homeassistantedupage#104]
After updating to version v0.5.2, I am unfortunately no longer receiving data from Edupage and am getting the following error.

Fehlertext (mit 'NoneType' object has no attribute 'encode'')

HA Version Core 2026.9.0
Operating System 18.2
Supervisor 2026.08.0

**Comment by rine77** [comment]
Thank you for reporting this. This looks very similar to #94, where a failure while loading grades causes the coordinator data to be discarded and the subsequent sensor setup receives no student name.

Could you please provide the complete sanitized traceback and a few preceding log lines containing homeassistantedupage? In particular, it would be helpful to know whether a get_grades() error occurs immediately before the NoneType/encode exception.

I have created a branch to work on #94. If the traceback confirms the same error path, I will track and fix both reports together there.

PR #103 is related to state restoration after restarts or temporary outages, but it does not address this setup-time initialization failure.

**Comment by nicknick25** [comment]
2026-09-04 01:27:22.545 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 01:57:24.538 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 02:27:26.372 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 02:57:28.564 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 03:27:30.555 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 03:57:32.487 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 04:27:34.401 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 04:57:36.348 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 05:27:38.400 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 05:57:40.405 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 06:27:42.425 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 06:57:44.424 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 07:27:46.443 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 07:57:48.431 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: list index out of range
2026-09-04 08:05:06.829 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homeassistantedupage which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2026-09-04 08:05:30.101 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homeassistantedupage which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2026-09-04 08:05:47.745 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__
2026-09-04 08:09:21.815 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__
2026-09-04 08:09:52.031 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__

**Comment by rine77** [comment]
Thank you for providing the additional log output.

The traceback confirms the immediate cause of the sensor setup failure:

```text
sensor.py, line 62: EduPageNotificationSensor(...)
sensor.py, line 165: unidecode(student_name)
```

The notification sensor is receiving `student_name=None`, and passing that value to `unidecode()` causes the `'NoneType' object has no attribute 'encode'` exception.

This is closely related to #94. However, the provided log does not yet show why the student name is missing. In #94, this happened after `get_grades()` failed and the coordinator discarded all previously loaded data. Here, the relevant preceding error may not be included in the excerpt.

Could you please provide the log lines immediately before one of the sensor setup failures, particularly any lines containing:

```text
INIT No matching student
INIT Failed
get_grades
```

The repeated `get_meals()` errors appear to be a separate issue. Version 0.5.2 catches these meal-fetch failures per day, so they should no longer abort the complete integration setup, although the underlying EduPage API error is still logged.

I have already created a branch for #94. The planned fix will make sensor setup robust when the coordinator contains incomplete data, use the stored student name or student ID as a fallback, and prevent `unidecode(None)` entirely. If the additional log lines confirm the same error path, #94 and this issue can be fixed together.

**Comment by bbirnbach** [comment]
Hi folks,

i can confirm there's some sort of problem with the latest release (0.5.2).
After complete reinitialize  the login process (delete integration completely and reinstall and login), this is all i can find the in the logs:

```
2026-09-04 08:42:13.441 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
2026-09-04 08:42:13.441 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-04: EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
2026-09-04 08:42:13.543 ERROR (MainThread) [custom_components.homeassistant_edupage] INIT Failed: 'list' object has no attribute 'snack'
2026-09-04 08:42:13.546 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
    EduPageNotificationSensor(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        coordinator, student.get("id"), student.get("name"), notifications
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__
    self._student_name = unidecode(student_name).replace(" ", "_").lower()
                         ~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/unidecode/__init__.py", line 60, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
```

Hope this helps!

**Comment by nicknick25** [comment]
`2026-09-04 08:09:21.812 ERROR (MainThread) [custom_components.homeassistant_edupage] INIT Failed: 'list' object has no attribute 'snack'
2026-09-04 08:09:21.815 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
    EduPageNotificationSensor(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        coordinator, student.get("id"), student.get("name"), notifications
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__
    self._student_name = unidecode(student_name).replace(" ", "_").lower()
                         ~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/unidecode/__init__.py", line 60, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
2026-09-04 08:09:52.029 ERROR (MainThread) [custom_components.homeassistant_edupage] INIT Failed: 'list' object has no attribute 'snack'
2026-09-04 08:09:52.031 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/homeassistantedupage/sensor.py", line 62, in async_setup_entry
    EduPageNotificationSensor(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        coordinator, student.get("id"), student.get("name"), notifications
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/homeassistantedupage/sensor.py", line 165, in __init__
    self._student_name = unidecode(student_name).replace(" ", "_").lower()
                         ~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/unidecode/__init__.py", line 60, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
2026-09-04 08:13:03.155 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2577210591888] Error handling message: expected '5minute' or 'hour' or 'day' or 'week' or 'month' or 'year' at 'period'. Got {'calendar': {'period': 'day'}} (invalid_format) Nicolas from 192.168.178.26 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36)
2026-09-04 08:13:37.953 ERROR (MainThread) [homeassistant] Error doing job: ClientConnectionResetError exception in shielded future (task: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/aiohttp/_websocket/writer.py", line 239, in _send_compressed_frame_async_locked
    self._write_websocket_frame(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<8 lines>...
        0x40,
        ^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/aiohttp/_websocket/writer.py", line 150, in _write_websocket_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport
2026-09-04 08:39:53.506 ERROR (MainThread) [custom_components.homeassistant_edupage] INIT Failed: 'list' object has no attribute 'snack'`

**Comment by rine77** [comment]
Thank you for the additional logs and for helping to identify the problem.

It turned out that the `v0.5.2` release tag accidentally pointed to the previous v0.5.1 commit. As a result, installations of v0.5.2 did not actually contain the fixes for missing student names and empty meal data, even though those fixes had already been merged into `main`.

I have now published **v0.5.3** with the correct code.

Could you please update to v0.5.3, restart Home Assistant, and let me know whether the following errors are gone?

* `'list' object has no attribute 'snack'`
* `'list' object has no attribute 'keys'`
* `'NoneType' object has no attribute 'encode'`

I will leave this issue open until we have confirmation that v0.5.3 resolves the problem.

**Comment by bbirnbach** [comment]
for me it works with 0.5.3 

there are a lot logs like this:

```
2026-09-04 09:24:04.919 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
2026-09-04 09:24:04.919 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-04: EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.224 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-07: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.224 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-07: EDUPAGE error updating get_meals() data for 2026-09-07: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.323 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-08: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.323 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-08: EDUPAGE error updating get_meals() data for 2026-09-08: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.434 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-09: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.434 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-09: EDUPAGE error updating get_meals() data for 2026-09-09: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.522 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-10: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.522 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-10: EDUPAGE error updating get_meals() data for 2026-09-10: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.653 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-11: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.653 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-11: EDUPAGE error updating get_meals() data for 2026-09-11: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.992 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-14: 'list' object has no attribute 'keys'
2026-09-04 09:24:05.993 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-14: EDUPAGE error updating get_meals() data for 2026-09-14: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.093 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-15: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.093 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-15: EDUPAGE error updating get_meals() data for 2026-09-15: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.228 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-16: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.228 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-16: EDUPAGE error updating get_meals() data for 2026-09-16: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.331 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-17: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.332 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-17: EDUPAGE error updating get_meals() data for 2026-09-17: 'list' object has no attribute 'keys'
2026-09-04 09:24:06.744 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.edupage_notification_XXX exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2026-09-04 09:24:09.237 ERROR (MainThread) [custom_components.homeassistantedupage.homeassistant_edupage] EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
2026-09-04 09:24:09.237 WARNING (MainThread) [custom_components.homeassistant_edupage] Failed to fetch meals data for 2026-09-04: EDUPAGE error updating get_meals() data for 2026-09-04: 'list' object has no attribute 'keys'
```

but I think it's ok because our school does not provide meal data...

**Comment by rine77** [comment]
too many ERROR/WARNING due to missing meals is fixed in 0.5.4 release.

**Comment by nicknick25** [comment]
Version 0.5.4 is running perfectly for me.

**Comment by rine77** [comment]
Thank you again for reporting this and for testing the subsequent releases.

The original setup failure (`'NoneType' object has no attribute 'encode'`) was resolved in v0.5.3, and the excessive meal-related error logging for schools without meal data was addressed in v0.5.4. The reporter has confirmed that v0.5.4 is running correctly.

Version 0.5.5 adds further resilience through state restoration after restarts or temporary EduPage outages.

I am therefore closing this issue as resolved. Please feel free to open a new issue if the problem appears again with the latest release.
